import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header.js';
import Feed from '../components/Feed';
import { useSession, signIn, signOut } from "next-auth/react";
import {useState, useEffect} from "react";


export default function Home({}) {
  const {data: session} = useSession();
  console.log(session);
  const [user, setUser] = useState();

  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">

      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Instagram_icon.png" />
      </Head>

      <Header />
      <>
            <h1>{session ? "{session.email} is here" : "No one is Here"}</h1>
            {session ? <button onClick={()=> signOut("")}>Logout</button>:<button onClick={()=> signIn("google")}>Login</button>}
        </>
      <Feed />
    </div>
  )
}

